[project]
name = "skimage-in-jax"
version = "0.1.1"
description = "Selected algorithms from scikit-image implemented in jax"
readme = "README.md"
dependencies = [
  "jax>=0.4.35",
  "jaxtyping>=0.2.37",
  "pytest>=8.3.4",
  "scikit-image>=0.25.0",
]
