[project]
name = "skimage-in-jax"
version = "0.1.0"
description = "Selected algorithms from scikit-image implemented in jax"
readme = "README.md"
dependencies = ["jax>=0.5.0", "pytest>=8.3.4", "scikit-image>=0.25.0"]
